name: Auto Test Generator

on:
  push:
    branches:
      - main
      - master

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. JDK installieren
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3. UTBot CLI herunterladen (falls nicht im Repo)
      - name: Download UTBot CLI
        run: |
          wget https://github.com/UnitTestBot/UTBotJava/releases/download/v0.8.1/utbot-cli.jar

      # 4. Tests generieren
      - name: Generate Tests
        run: |
          mkdir -p src/test/java
          java -jar utbot-cli.jar --generate-tests src/main/java --tests-directory src/test/java

      # 5. Änderungen committen (nur wenn Änderungen vorhanden)
      - name: Commit generated tests
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          if [ -n "$(git status --porcelain)" ]; then
            git add src/test/java
            git commit -m "Auto-generated tests"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
